name: azureml-enterprise-mlops
channels: [conda-forge]
dependencies:
  - python=3.10
  - pip
  - pip:
      - azureml-mlflow>=1.57,<2
      - mlflow>=3.15,<4
      - pandas>=2.2,<3
      - pyarrow>=23.0.1,<24
      - scikit-learn>=1.5,<2
